fix(component/breadcrumb): correct the size of the breadcrumb links
adeo/mozaic-design-system pull request #1006
Opened 2022-01-17 22:10 UTC by tiloyi

## I have read [the contributing guidelines](https://mozaic.adeo.cloud/Contributing/)

- [ ] Yes
- [ ] No

## Does this PR introduce a [breaking change](https://mozaic.adeo.cloud/Contributing/Developers/GitConventions/#breaking-changes-)?

- [ ] Yes
- [ ] No

## Describe the changes

Correct the size of the breadcrumb links

2022-01-18 13:28 UTC, mohamedMok approved these changes

2022-02-01 17:09 UTC, mohamedMok approved these changes

2022-02-01 17:14 UTC, caqueste requested changes
Links are no longer centred with the icons :/

2022-02-02 08:21 UTC, tiloyi commented
> Links are no longer centred with the icons :/

Fixed

2022-02-02 09:02 UTC, caqueste approved these changes
🔥

2022-02-02 09:12 UTC, merged