feat(components/button): improve colour a11y
adeo/mozaic-design-system pull request #1165
Opened 2022-07-04 14:13 UTC by caqueste

## I have read [the contributing guidelines](https://mozaic.adeo.cloud/Contributing/)

- [x] Yes
- [ ] No

## Does this PR introduce a [breaking change](https://mozaic.adeo.cloud/Contributing/Developers/GitConventions/#breaking-changes-)?

- [ ] Yes
- [x] No

## Describe the changes

GitHub issue number or Jira issue URL: N/A

## Other information

2022-07-06 09:04 UTC, Marine-Fabien requested changes
In the end, you don't change the colour labels of the disabled?

2022-07-12 11:51 UTC, caqueste commented
@Marine-Fabien No. As disabled elements should not be accessible, I need more data to avoid users confusing it with an active button.
We currently provide these buttons with a 3:1 contrast ratio. It's better than nothing 😉 

We'll open the issue when we've got more data.

2022-08-23 12:05 UTC, Marine-Fabien approved these changes

2022-11-02 11:31 UTC, tiloyi commented
Replaced by https://github.com/adeo/mozaic-design-system/pull/1245

2022-11-02 11:31 UTC, closed without merging