docs(tabs): use Mozaic tabs in docs
adeo/mozaic-design-system pull request #1340
Opened 2023-01-23 15:20 UTC by mohamedMok

## I have read [the contributing guidelines](https://mozaic.adeo.cloud/Contributing/)

- [ ] Yes
- [ ] No

## Does this PR introduce a [breaking change](https://mozaic.adeo.cloud/Contributing/Developers/GitConventions/#breaking-changes-)?

- [ ] Yes
- [ ] No

## Describe the changes

GitHub issue number or Jira issue URL: N/A

## Other information

2023-01-25 08:50 UTC, tiloyi approved these changes

2023-01-25 08:50 UTC, tiloyi commented
🔥 🔥 🔥

2023-02-02 13:23 UTC, caqueste requested changes
@mohamedMok Great idea!
I have feedback regarding the underline of the selected tab. The width isn't the right one 😕
<img width="706" alt="Capture d’écran 2023-02-02 à 14 21 01" src="https://user-images.githubusercontent.com/43212270/216336659-b9c88c4c-f843-4f72-93df-e1b691496102.png">

2023-02-13 09:26 UTC, caqueste approved these changes
🔥 🔥

2023-02-13 15:59 UTC, merged