docs(datatable): fix mass selection behaviour
adeo/mozaic-design-system pull request #1503
Opened 2023-10-16 12:53 UTC by JBPTST

## I have read [the contributing guidelines](https://mozaic.adeo.cloud/Contributing/)

- [X] Yes
- [ ] No

## Does this PR introduce a [breaking change](https://mozaic.adeo.cloud/Contributing/Developers/GitConventions/#breaking-changes-)?

- [ ] Yes
- [X] No

## Describe the changes

GitHub issue number or Jira issue URL: https://github.com/adeo/mozaic-web-components/issues/764

## Other information
Figma prototype: https://www.figma.com/proto/Fwvg2vuovdgIZZudFzwmLG/02.-Datatable-%F0%9F%94%B5?page-id=578%3A79523&type=design&node-id=3849-51504&viewport=193%2C-128%2C0.26&t=CbFkLJpaf5KhOoRb-1&scaling=min-zoom&starting-point-node-id=3849%3A51504&mode=design

2023-10-16 13:00 UTC, slaoutadeo commented
![Logo](https://user-images.githubusercontent.com/42570337/152954017-2101d077-2be7-48a8-8d34-618fe5a7c779.png)
**Checkmarx One – Scan Summary & Details** – [5658c04e\-2a8f\-414f\-8c19\-b62398ed2408](https://eu.ast.checkmarx.net/projects/d2ea2837-0ed1-4404-8c6a-f1a1376ffd05/scans?id=5658c04e-2a8f-414f-8c19-b62398ed2408&branch=docs-massselection-datatable)
### New Issues
Severity|Issue|Source File / Package|Checkmarx Insight
---|---|---|---
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[CVE-2023-4863](https://devhub.checkmarx.com/cve-details/CVE-2023-4863)|Npm\-sharp\-0\.30\.7|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/d2ea2837-0ed1-4404-8c6a-f1a1376ffd05/reports/5658c04e-2a8f-414f-8c19-b62398ed2408/vulnerabilities/CVE-2023-4863%3ANpm-sharp-0.30.7/vulnerabilityDetails)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[CVE-2023-26364](https://devhub.checkmarx.com/cve-details/CVE-2023-26364)|Npm\-@adobe/css\-tools\-4\.2\.0|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/d2ea2837-0ed1-4404-8c6a-f1a1376ffd05/reports/5658c04e-2a8f-414f-8c19-b62398ed2408/vulnerabilities/CVE-2023-26364%3ANpm-%40adobe%2Fcss-tools-4.2.0/vulnerabilityDetails)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[CVE-2023-44270](https://devhub.checkmarx.com/cve-details/CVE-2023-44270)|Npm\-postcss\-8\.4\.24|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/d2ea2837-0ed1-4404-8c6a-f1a1376ffd05/reports/5658c04e-2a8f-414f-8c19-b62398ed2408/vulnerabilities/CVE-2023-44270%3ANpm-postcss-8.4.24/vulnerabilityDetails)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[CVE-2023-44270](https://devhub.checkmarx.com/cve-details/CVE-2023-44270)|Npm\-postcss\-7\.0\.39|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/d2ea2837-0ed1-4404-8c6a-f1a1376ffd05/reports/5658c04e-2a8f-414f-8c19-b62398ed2408/vulnerabilities/CVE-2023-44270%3ANpm-postcss-7.0.39/vulnerabilityDetails)
![MEDIUM](https://user-images.githubusercontent.com/42570337/152952809-c4159077-9c06-4ed9-bb5c-894799acf2d4.png)|[CVE-2023-44270](https://devhub.checkmarx.com/cve-details/CVE-2023-44270)|Npm\-postcss\-7\.0\.36|[Vulnerable Package](https://eu.ast.checkmarx.net/sca/#/projects/d2ea2837-0ed1-4404-8c6a-f1a1376ffd05/reports/5658c04e-2a8f-414f-8c19-b62398ed2408/vulnerabilities/CVE-2023-44270%3ANpm-postcss-7.0.36/vulnerabilityDetails)

### Fixed Issues
Severity|Issue|Source File / Package
---|---|---
![HIGH](https://user-images.githubusercontent.com/42570337/152952546-9232b4c8-a6bb-44a6-8d55-ba676b398731.png)|[CVE-2023-2251](https://devhub.checkmarx.com/cve-details/CVE-2023-2251)|Npm\-yaml\-1\.10\.2

2023-10-16 14:46 UTC, caqueste requested changes
@JBPTST Just a quick change in the sentence structure

2023-10-16 14:46 UTC, caqueste commented on src/docs/Components/DataTable/index.mdx
> +Once users select all rows of a page, a dedicated banner for mass selection will appear, allowing them to select all rows in the table, including all pages.
~~Once users select all rows of a page~~
Once users have selected all the rows on a page,

2023-10-17 12:28 UTC, mohamedMok approved these changes

2023-10-17 12:28 UTC, merged