[WIP] fix(patterns/fonts): update LM webfonts
adeo/mozaic-design-system pull request #616
Opened 2020-07-29 15:22 UTC by tiloyi

## I have read [the contributing guidelines](https://mozaic.adeo.cloud/Contributing/)

- [x] Yes
- [ ] No

## Does this PR introduce a [breaking change](https://mozaic.adeo.cloud/Contributing/Developers/GitConventions/#breaking-changes-)?

- [ ] Yes
- [ ] No

## Describe the changes

GitHub issue number or Jira issue URL: N/A

## Other information

2020-09-30 09:40 UTC, nherwegh requested changes
**Modals**
all text: 5px lower
link case: 2px higher

2020-09-30 09:40 UTC, nherwegh commented on packages/styles/components/_c.breadcrumb.scss
> +  padding: $mu100 0 magic-unit-rem(0.875, 'true') magic-unit-rem(1.125, 'true');
links: 3px higher

2020-10-01 08:52 UTC, nherwegh requested changes

2020-10-01 08:52 UTC, nherwegh commented on packages/styles/components/_c.tooltip.scss
> +    padding: magic-unit-rem(0.4375, true) $mu100;
tooltip text should be `2px higher`

2020-10-01 08:52 UTC, nherwegh commented on packages/styles/components/_c.tabs.scss
> +    padding: magic-unit-rem(1.1875, true) $mu150;
tabs text should be `3px higher`

2020-10-23 08:27 UTC, nherwegh commented
@tiloyi `tabs` and `tooltips` are OK AY! 🎉

2020-10-27 14:15 UTC, nherwegh commented
@tiloyi everything seems fine except the open accordion text `line-height` that should be large -> 1.5rem if I'm not wrong

2020-10-27 16:41 UTC, caqueste approved these changes

2020-10-28 08:56 UTC, nherwegh approved these changes

2020-10-28 09:08 UTC, merged