feat(website/roadmap): update the roadmap
adeo/mozaic-design-system pull request #622
Opened 2020-08-19 12:28 UTC by caqueste

## I have read [the contributing guidelines](https://mozaic.adeo.cloud/Contributing/)

- [x] Yes
- [ ] No

## Does this PR introduce a [breaking change](https://mozaic.adeo.cloud/Contributing/Developers/GitConventions/#breaking-changes-)?

- [ ] Yes
- [x] No

## Describe the changes

GitHub issue number or Jira issue URL: N/A

## Other information

2020-08-19 13:17 UTC, nherwegh requested changes

2020-08-19 13:17 UTC, nherwegh commented on src/docs/Updates/Roadmap/index.mdx
> +**Mozaic-Figma:**
can we rephrase like that?
⬇️

Mozaic-Figma add ons:

- All form patterns
- Flags
- Dividers
- Breadcrumb
- Pagination
- Tabs
- Tooltips

2020-08-19 14:09 UTC, nherwegh approved these changes

2020-08-24 09:25 UTC, nherwegh requested changes
<img width="340" alt="image" src="https://user-images.githubusercontent.com/27195157/91027475-6fe4b400-e5fc-11ea-95fa-9649f7e4299e.png">
still have the list layout 😣

2020-08-24 10:18 UTC, nherwegh approved these changes

2020-08-25 08:05 UTC, tiloyi approved these changes

2020-09-01 12:48 UTC, mohamedMok approved these changes

2020-09-01 13:19 UTC, merged