[WIP] feat(website/toc): improve table of content styles
adeo/mozaic-design-system pull request #629
Opened 2020-08-25 16:12 UTC by tiloyi

## I have read [the contributing guidelines](https://mozaic.adeo.cloud/Contributing/)

- [x] Yes
- [ ] No

## Does this PR introduce a [breaking change](https://mozaic.adeo.cloud/Contributing/Developers/GitConventions/#breaking-changes-)?

- [ ] Yes
- [x] No

## Describe the changes

Improve Table Of Content

GitHub issue number or Jira issue URL: [ID-5542](https://adeo.kanbanize.com/ctrl_board/10/cards/5542/details/)

## Other information

2020-08-26 16:13 UTC, caqueste requested changes
**A few feedbacks:**
1. When we scroll the space between the header and the TOC goes from 16px to 5px.
2. Thanks for the effects when we scroll, but in the following scenario, it didn't work → When I click on an item, then if I scroll the item still is active.
![bug-scroll](https://zupimages.net/up/20/35/mxc7.png)
3. Question for all: Do we show the third level on the TOC?

2020-08-28 07:43 UTC, tiloyi commented
@caqueste I've corrected all of your returns, I'll let you check if it's good for you. 

As for your question, I think we should keep the third level

2020-08-28 09:25 UTC, caqueste approved these changes

2020-08-28 09:28 UTC, nherwegh reviewed
well done ✨

2020-08-28 09:29 UTC, nherwegh approved these changes

2020-08-31 14:21 UTC, mohamedMok approved these changes

2020-08-31 14:54 UTC, merged