feat(docs): upgrade readme
adeo/mozaic-design-system pull request #652
Opened 2020-10-06 12:41 UTC by mohamedMok

## I have read [the contributing guidelines](https://mozaic.adeo.cloud/Contributing/)

- [ ] Yes
- [ ] No

## Does this PR introduce a [breaking change](https://mozaic.adeo.cloud/Contributing/Developers/GitConventions/#breaking-changes-)?

- [ ] Yes
- [ ] No

## Describe the changes

GitHub issue number or Jira issue URL: N/A

## Other information

2020-10-06 13:23 UTC, nherwegh requested changes

2020-10-06 13:23 UTC, nherwegh commented on README.md
>  We tried to focus on the developper experience, meaning that working with it should be as simple as possible.
developer

2020-10-06 15:03 UTC, nherwegh approved these changes

2020-10-14 07:53 UTC, tiloyi commented on README.md
> +> improve quality of deliverables and thus help set up a coherent customer experience.
> Mozaic is an open-source design system built by Adeo; to reinforce team’s delivery time, improve quality of deliverables and thus help set up a coherent customer experience.

2020-10-14 07:53 UTC, tiloyi commented on README.md
> +- [React](https://github.com/adeo/mozaic-react)
Personally, I wouldn't mention the React version because nobody uses it.

2020-10-14 07:53 UTC, tiloyi commented on README.md
> +| [`@mozaic-ds/styles`](./packages/styles)                 | All the CSS and SCSS files that constitute the Mozaic SCSS framework.
All the SCSS source files

2020-10-14 07:53 UTC, tiloyi commented on README.md
> +| [`@mozaic-ds/tokens`](./packages/tokens)                 | Tokens are theming/styling constants defined in a JSON file. They are trasnpiled into multiple format to be shared across plateforms (SCSS
~~trasnpiled~~ => transpiled

2020-10-14 07:53 UTC, tiloyi commented on README.md
> +| [`@mozaic-ds/css-dev-tools`](./packages/css-dev-tools)     | Right now the tools are composed only of SCSS/PostCSS tools.
~~Right now the tools are composed only of SCSS/PostCSS tools.~~
=> Tools for css like PostCSS plugins and linters config

2020-10-14 07:53 UTC, tiloyi commented on README.md
> +| [`@mozaic-ds/web-fonts`](./packages/web-fonts)         | All fonts available in MDS (LM fonts currently)
~~LM fonts currently~~
=> Currently, the Leroy Merlin font only

2020-10-14 08:18 UTC, merged