feat(pattern/tags): update tags size to 40
adeo/mozaic-design-system pull request #656
Opened 2020-10-14 14:46 UTC by mohamedMok

## I have read [the contributing guidelines](https://mozaic.adeo.cloud/Contributing/)

- [ ] Yes
- [ ] No

## Does this PR introduce a [breaking change](https://mozaic.adeo.cloud/Contributing/Developers/GitConventions/#breaking-changes-)?

- [ ] Yes
- [ ] No

## Describe the changes

GitHub issue number or Jira issue URL: N/A

## Other information

2020-10-15 09:36 UTC, nherwegh requested changes

2020-10-15 09:36 UTC, nherwegh commented on packages/styles/components/_c.tag.scss
> +          padding: $mu050 $mu100 $mu050 $mu125;
the size of this icon should be `24px`
it seems that it's 32px here

2020-10-16 08:10 UTC, nherwegh approved these changes

2020-10-19 08:48 UTC, caqueste requested changes
There is a mistake on the removable tags, the cross colour must use the G800.
The rest is OK 😉

2020-10-19 14:46 UTC, tiloyi commented on packages/styles/settings-tools/_s.tag.scss
> +    'border-radius': 1.25rem,
~~1.25rem~~ => $mu125

2020-10-20 13:16 UTC, merged