feat(foundations/font): add a parameter to the import-font-families()…
adeo/mozaic-design-system pull request #723
Opened 2021-01-14 16:48 UTC by tiloyi

… mixin

Resolves #695

## I have read [the contributing guidelines](https://mozaic.adeo.cloud/Contributing/)

- [x] Yes
- [ ] No

## Does this PR introduce a [breaking change](https://mozaic.adeo.cloud/Contributing/Developers/GitConventions/#breaking-changes-)?

- [x] Yes
- [ ] No

## Describe the changes

GitHub issue number or Jira issue URL: Resolves [ISSUE-695](https://github.com/adeo/mozaic-design-system/issues/695)

## Other information

2021-01-15 10:04 UTC, nherwegh requested changes

2021-01-15 10:04 UTC, nherwegh commented on src/docs/Foundations/Typography/FontFamilies/code.mdx
> +The `set-font-weight()` mixin allows you to set the font weight you wish to use in your selector.
<s>wish</s> ➡️ want

2021-01-15 14:21 UTC, Marine-Fabien approved these changes

2021-01-18 08:16 UTC, tiloyi commented on src/docs/Foundations/Typography/FontFamilies/code.mdx
> +  code when using the components and tools supplied by Mozaic.
fixed

2021-01-18 08:16 UTC, tiloyi commented on src/docs/Foundations/Typography/FontFamilies/code.mdx
> +In order to use the font proposed in Mozaic in your code, start by importing the `_all-settings.scss` file in the following way:
fixed

2021-01-18 08:16 UTC, tiloyi commented on src/docs/Foundations/Typography/FontFamilies/code.mdx
> +## Details of the mixins
fixed

2021-01-18 08:19 UTC, tiloyi commented on src/docs/Foundations/Typography/FontFamilies/code.mdx
> +The `set-font-weight()` mixin allows you to set the font weight you wish to use in your selector.
fixed

2021-01-18 08:19 UTC, tiloyi commented on src/docs/Foundations/Typography/FontFamilies/code.mdx
> +### The import-font-families() mixin
fixed

2021-01-18 14:37 UTC, mohamedMok approved these changes

2021-01-18 17:48 UTC, merged