[WIP] refactor(accordions): add small accordions case
adeo/mozaic-design-system pull request #726
Opened 2021-01-27 15:15 UTC by nherwegh

## I have read [the contributing guidelines](https://mozaic.adeo.cloud/Contributing/)

- [x] Yes
- [ ] No

## Does this PR introduce a [breaking change](https://mozaic.adeo.cloud/Contributing/Developers/GitConventions/#breaking-changes-)?

- [ ] Yes
- [x] No

## Describe the changes

GitHub issue number or Jira issue URL: N/A

## Other information

2021-01-27 15:18 UTC, nherwegh commented
🧠 reminder: 
@tiloyi or @MohamedHedi, can we add a preview with the small and the medium version is the usage documentation

2021-02-03 08:52 UTC, caqueste requested changes

2021-02-03 08:52 UTC, caqueste commented on src/docs/Components/Accordion/index.mdx
> +Always think about accessibility when you use smaller text content sizes.
~~when you use smaller text content sizes~~ when you use the smaller accordion sizes

2021-02-03 09:41 UTC, caqueste approved these changes

2021-02-03 09:42 UTC, merged