feat(patterns/notifications): add usage documentation
adeo/mozaic-design-system pull request #739
Opened 2021-02-18 12:35 UTC by caqueste

## I have read [the contributing guidelines](https://mozaic.adeo.cloud/Contributing/)

- [x] Yes
- [ ] No

## Does this PR introduce a [breaking change](https://mozaic.adeo.cloud/Contributing/Developers/GitConventions/#breaking-changes-)?

- [ ] Yes
- [x] No

## Describe the changes

GitHub issue number or Jira issue URL: N/A

## Other information

2021-02-18 15:03 UTC, nherwegh requested changes

2021-02-18 15:03 UTC, nherwegh commented on src/docs/Components/Notification/index.mdx
> +Note that only medium notifications can be closable.
Closable notification can be used with the medium size variation only.

2021-02-22 09:01 UTC, nherwegh approved these changes

2021-02-24 15:05 UTC, tiloyi approved these changes

2021-03-02 10:56 UTC, merged