fix(onboard/link): fix typo for link mixin
adeo/mozaic-design-system pull request #761
Opened 2021-03-08 15:50 UTC by mohamedMok

## I have read [the contributing guidelines](https://mozaic.adeo.cloud/Contributing/)

- [ ] Yes
- [ ] No

## Does this PR introduce a [breaking change](https://mozaic.adeo.cloud/Contributing/Developers/GitConventions/#breaking-changes-)?

- [ ] Yes
- [ ] No

## Describe the changes

GitHub issue number or Jira issue URL: N/A

## Other information

2021-03-08 16:54 UTC, ChristopheHusquin requested changes

2021-03-08 16:54 UTC, ChristopheHusquin commented on src/docs/Components/Links/code.mdx
>    'active': blue}
```suggestion
  'active': blue
```

2021-03-09 09:58 UTC, mohamedMok commented on src/docs/Components/Links/code.mdx
>    'active': blue}
20298ba

2021-03-09 14:46 UTC, tiloyi approved these changes

2021-03-09 15:33 UTC, merged