fix(pattern/accordion): add transition on content
adeo/mozaic-design-system pull request #770
Opened 2021-03-17 15:38 UTC by mohamedMok

## I have read [the contributing guidelines](https://mozaic.adeo.cloud/Contributing/)

- [ ] Yes
- [ ] No

## Does this PR introduce a [breaking change](https://mozaic.adeo.cloud/Contributing/Developers/GitConventions/#breaking-changes-)?

- [ ] Yes
- [ ] No

## Describe the changes

GitHub issue number or Jira issue URL: N/A

## Other information

2021-03-25 11:01 UTC, caqueste requested changes
Can you test the animation on the closing with the same effect as on the opening?

2021-03-25 13:18 UTC, matthieu-castier commented
It seems good to me. Tested on https://leroymerlin-10122202-frlm-uat1.nprd-02-a9ef.priv.manawa.adeo.cloud/services/service-client/livraison-a-domicile.html

2021-03-25 13:24 UTC, matthieu-castier approved these changes

2021-03-25 14:19 UTC, tiloyi approved these changes

2021-03-30 08:04 UTC, caqueste approved these changes

2021-03-30 09:21 UTC, merged