feat(patterns): a11y - standardize focus states
adeo/mozaic-design-system pull request #788
Opened 2021-04-10 11:18 UTC by tiloyi

## I have read [the contributing guidelines](https://mozaic.adeo.cloud/Contributing/)

- [x] Yes
- [ ] No

## Does this PR introduce a [breaking change](https://mozaic.adeo.cloud/Contributing/Developers/GitConventions/#breaking-changes-)?

- [ ] Yes
- [x] No

## Describe the changes

Standardise the focus state

GitHub issue number or Jira issue URL: [MZC-6](https://jira.adeo.com/browse/MZC-6)

## Other information

2021-04-12 13:00 UTC, caqueste requested changes
Great work @tiloyi 💪

Just a few changes.
- Quantity selector: Can we always have the focus on the foreground?
- Tags: Can we remove the white outline? It's visible with a dark background.
- I forgot the tooltip triggered by an icon. The board is now updated ;)

2021-04-12 19:07 UTC, tiloyi commented
> Great work @tiloyi 💪
> 
> Just a few changes.
> 
> * Quantity selector: Can we always have the focus on the foreground?
> * Tags: Can we remove the white outline? It's visible with a dark background.
> * I forgot the tooltip triggered by an icon. The board is now updated ;)

@caqueste I have fixed the following points : 
- Quantity selector: Can we always have the focus on the foreground?
- Tags: Can we remove the white outline? It's visible with a dark background.

For the remaining point, I'll let you keep me informed.

2021-04-13 14:22 UTC, mohamedMok approved these changes

2021-04-14 06:59 UTC, caqueste approved these changes

2021-04-14 08:30 UTC, merged