feat(onboard/install): update Sass requirements on dev documentation
adeo/mozaic-design-system pull request #871
Opened 2021-07-19 07:07 UTC by tiloyi

## I have read [the contributing guidelines](https://mozaic.adeo.cloud/Contributing/)

- [x] Yes
- [ ] No

## Does this PR introduce a [breaking change](https://mozaic.adeo.cloud/Contributing/Developers/GitConventions/#breaking-changes-)?

- [ ] Yes
- [x] No

## Describe the changes

Update Sass requirements on dev documentation

GitHub issue number or Jira issue URL: [MZC-104](https://jira.adeo.com/browse/MZC-104)

2021-07-20 16:01 UTC, caqueste requested changes

2021-07-20 16:08 UTC, tiloyi commented on src/docs/GetStarted/Developers/Installation/index.mdx
> +- `@mozaic-ds/source-directory-tree`: a Gatsby plugin to get the directory and file structure in order to build the styleguide menu
fixed

2021-07-20 16:09 UTC, tiloyi commented on src/docs/GetStarted/Developers/Installation/index.mdx
> +- `@mozaic-ds/source-pattern`: a Gatsby plugin build the live examples displayed in the styleguide
fixed

2021-07-20 16:09 UTC, tiloyi commented on src/docs/GetStarted/Developers/Installation/index.mdx
> +- `@mozaic-ds/theme-styleguide`: the Gatsby theme with the components and configuration used to build the styleguide UI
fixed

2021-07-20 16:09 UTC, tiloyi commented on src/docs/GetStarted/Developers/Installation/index.mdx
> +We also packaged [Gatsby](https://www.gatsbyjs.com/) extensions that we developed in order to create the styleguide website
fixed

2021-07-20 16:09 UTC, tiloyi commented on src/docs/GetStarted/Developers/Installation/index.mdx
> +- `@mozaic-ds/sketch-libraries`: the sketch designs files
fixed

2021-07-20 16:32 UTC, mohamedMok approved these changes

2021-07-21 08:34 UTC, caqueste approved these changes

2021-07-21 08:39 UTC, merged