feat(accordion): add variation with checkbox and toggle
adeo/mozaic-design-system pull request #912
Opened 2021-09-08 15:42 UTC by mohamedMok

## I have read [the contributing guidelines](https://mozaic.adeo.cloud/Contributing/)

- [x] Yes
- [ ] No

## Does this PR introduce a [breaking change](https://mozaic.adeo.cloud/Contributing/Developers/GitConventions/#breaking-changes-)?

- [ ] Yes
- [x] No

## Describe the changes

GitHub issue number or Jira issue URL: https://jira.adeo.com/browse/MZC-23

## Other information

2021-09-09 16:00 UTC, caqueste requested changes

2021-09-09 16:00 UTC, caqueste commented on src/docs/Components/Accordion/previews/selectable.preview.html
> +    <div class="mc-accordion__content">
@mohamedMok For the checkbox variation, the accordion title must have the checkbox label style 😉

2021-09-13 08:10 UTC, tiloyi commented on src/docs/Components/Accordion/previews/selectable.preview.html
> +    </label>
Unfortunately, this HTML structure is not semantic.

I think the easiest way would be to use the structure you made on Mozaic-Vue => https://github.com/adeo/mozaic-vue/blob/master/packages/vue/src/components/accordion/MAccordion.vue

2021-09-14 09:45 UTC, caqueste requested changes
Another bug or mistake, the padding-left of the small accordion changed to 40px (instead of 8px)

2021-09-14 09:45 UTC, caqueste commented on src/docs/Components/Accordion/code.mdx
> +<Preview path="selectable" />
@mohamedMok I have a problem with the toggle. When I clicked on it, it opened the accordion instead of switch to the checked state.

2021-09-14 15:07 UTC, caqueste approved these changes

2021-11-12 13:12 UTC, tiloyi approved these changes

2021-11-12 13:39 UTC, merged