refactor(onboard/glossary): reorder the glossary alphabetically
adeo/mozaic-design-system pull request #951
Opened 2021-10-28 05:21 UTC by tiloyi

## I have read [the contributing guidelines](https://mozaic.adeo.cloud/Contributing/)

- [x] Yes
- [ ] No

## Does this PR introduce a [breaking change](https://mozaic.adeo.cloud/Contributing/Developers/GitConventions/#breaking-changes-)?

- [ ] Yes
- [x] No

## Describe the changes

Reorder the glossary alphabetically

2021-11-04 13:30 UTC, caqueste requested changes

2021-11-04 13:30 UTC, caqueste commented on src/docs/Contributing/Principles/Glossary/index.mdx
> +Abstract is a software like GitHub, used by the designers to collaborate on design files.
@tiloyi You can remove Abstract. We stopped using it since we started to work with Figma 🙂

2021-11-08 10:27 UTC, mohamedMok approved these changes

2021-11-09 16:49 UTC, caqueste approved these changes

2021-11-09 19:54 UTC, merged